name: Terraform Multi-account Deploy workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform-job:
    environment: dev
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout/Clone repository
      uses: actions/checkout@v3

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.IAM_ROLE }}
        role-session-name: GitHubActionsTerraformSession

    - name: Deploy Terraform Code
      working-directory: root-module
      run: |
        terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" -input=false
        terraform plan -var-file=${{ vars.STAGE }}.tfvars -input=false
