name: Terraform Multi-account Deploy workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout/Clone repository
      uses: actions/checkout@v3

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: us-east-1
        #role-to-assume: arn:aws:iam::450558842433:role/github-actions-iam-role-dev
        role-to-assume: arn:aws:iam::058316962389:role/github-actions-iam-role-staging
        role-session-name: GitHubActionsTerraformSession

    - name: Deploy Terraform Code
      working-directory: root-module
      run: |
        terraform init -backend-config="practice-eks-058316962389-tfstate-staging" -input=false
        terraform plan -var-file=staging.tfvars -input=false
